#!/bin/bash
# test_file: evaluate the status of a file


FILE=~/.bashrc

if [ -e "$FILE" ];then
	echo "$FILE exists"
	if [ -f "$FILE" ];then
		echo "$FILE is a file"
	elif [ -d "$FILE" ];then
		echo "$FILE is a directory"
	fi

	if [ -r "$FILE" ];then
		echo "$FILE has read property"
	fi
	if [ -w "$FILE" ];then
		echo "$FILE has write property"
	fi
	if [ -x "$FILE" ];then
		echo "$FILE has executable property"
	fi
else
	echo "$FILE does not exist"
fi

exit
