#!/bin/bash

# read-multiple: read multiple values from the keyboard

echo -n "Enter one or more values -> "
read val1 val2 val3 val4 val5

echo "val1 = $val1"
echo "val2 = $val2"
echo "val3 = $val3"
echo "val4 = $val4"
echo "val5 = $val5"

