#!/bin/bash

# read-secret: Read user password after a specified period of time

read -t 5 -sp "Enter secret passphase -> " secret_pass
echo

if [ -z "$secret_pass" ];then
	echo "No input received, timeout or empty"
else
	echo "You enter a secret password: $secret_pass"
fi

exit

