#!/bin/bash

# read-multiple: read a bunch of information provided by the user

read -p "Please enter your information with this order: first_name last_name adress others -> " first_name last_name adress others

echo "Your first name is $first_name"
echo "Your last name is $last_name"
echo "Your adress is $adress"
echo "Other information: $others"

