#!/bin/bash

# read-ifs: read field from a file using ":" as a delimeter

FILE=/etc/passwd

read -p "Give me a username to search for -> " username 

FILE_INFO="$(grep -iE "^$username:" $FILE)"

if [ -z "$FILE_INFO" ];then
	echo "No such User with the name : $username" >&2
	exit 1
else
	OLD_IFS="$IFS"
	IFS=":"
	read username passwd uid gid info home shell <<< "$FILE_INFO"
	cat <<- 1EOF
		User:      $username
		UID:       $uid
		GID:	   $gid
		INFO:	   $info
		HOME DIR:  $home
		SHELL TYPE:$shell
	1EOF
	IFS="$OLD_IFS"
fi

exit



