#!/bin/bash

# validate-input: attach a bunch of functions to validate an input provided by the user
# Testing in terminal with: ->echo "-.-Hello_W1.orl-d9" | grep -E "^[-\._A-Za-z1-9]+$"
#			    ->echo "-15.602" | grep -E "^-?[0-9]+(\.[0-9]+)?$"
#			    ->echo "102" | grep -E "^-?[0-9]+$"

invalid_input(){
	echo "Invalid input $REPLY because $1" >&2
	exit 1
}

read -e -p "Enter a single item -> "

[ -z "$REPLY" ] && invalid_input "Empty input"

(("$(echo $REPLY | wc -w)" > 1)) && invalid_input "Multiple Input"

if [[ "$REPLY" =~ ^[-\._A-Za-z0-9]+$ ]];then
	echo "$REPLY is a valid Filename"
	if [ -e "$REPLY" ];then
		echo "And file $REPLY exists"
	else
		echo "However, $REPLY does not exists"
	fi

	# Check if the input is a number
	if [[ "$REPLY" =~ ^-?[0-9]+(\.[0-9]+)?$ ]];then
		echo "$REPLY is a Number"
	else
		echo "$REPLY isn't a Number"
	fi

	# Check if the input is an integer
	if [[ "$REPLY" =~ ^-?[0-9]+$ ]];then
		echo "$REPLY is an Integer"
	else
		echo "$REPLY isn't an Integer"
	fi

else
	echo "Error: $REPLY is not a valid Filename" >&2
	exit 1
fi

exit
