#!/bin/bash

# Chosen menu: execute command depends on user chosen menu number


clear
echo "
Please select:
	1. Display system information
	2. Display Disk Space Information
        3. Display Home Space Utilization	
	0. Quit
"

read -e -p "Enter selection [0-3] -> "

if [[ "$REPLY" =~ ^[0-3]$ ]];then
	if [[ "$REPLY" == 0 ]];then
		echo "Program terminated. Have a great day !!!"
		exit
	fi

	if [[ "$REPLY" == 1 ]];then
                echo "Hostname: $HOSTNAME"
		uptime
        fi

	if [[ "$REPLY" == 2 ]];then
                echo "Hostname: $HOSTNAME"
                df -h
        fi

	if [[ "$REPLY" == 3 ]];then
		if (("$(id -u)" == 0));then
			echo "Home Space Utilization for All Users"
			du -sh /home/*	
		else
			echo "Home Space Utilization for $USER"
			du -sh $HOME
		fi
	fi

else
	echo "Invalid entry, please choose number between 0 and 3" >&2
	exit 1
fi

exit


