#!/bin/bash

# make a bunch of confirmation process before the deletion

read -e -p "Enter Directory Name -> " dir_name

message_output(){
	echo $1 >&2
	exit 1
}

if [ -z "$dir_name" ];then
	message_output "You entered nothing"
fi

if [ -d "$dir_name" ];then
	if ! cd "$dir_name";then
		message_output "Can not enter to the $dir_name"
	else
		rm *
		echo "Job ended with success"
	fi
else
	message_output "No such directory with name $dir_name"
fi

echo "Program Ended !!!"

