#!/bin/bash

# Try working with CASE

shopt -s extglob   # enable extended globs like (grep -E)

read -e -p "Enter something -> "

case "$REPLY" in
	+([A-Za-z ]))	echo "You entered a Word"
		;;
	+([0-9]))	echo "You entered a Number"
		;;
	*.txt)		echo "$REPLY is a word ending with txt"
                ;;
	*)		echo "$REPLY is something else"
		;;
esac




