#!/bin/bash
# Script to view all positional paremeters

echo "
Number of arguments: $#
Fullname: "$0"
Basename: "$(basename $0)"
Dirname: "$(dirname $0)"
Basename pure shell: "${0##*/}"
\$1: $1
\$2: $2
\$3: $3
\$4: $4
\$5: $5
\$6: $6
\$7: $7
\$8: $8
\$9: $9
\$10: ${10}
\$11: ${11}
\$12: ${12}


"


