#!/bin/bash

# display and tranfer positional parameter

print_params(){
	echo "\$1 = $1"
	echo "\$2 = $2"
	echo "\$3 = $3"
	echo "\$4 = $4"
	echo "\$5 = $5"
	echo "\$6 = $6"
}

pass_params(){
	echo -e "\n" '$*'; print_params $*
	echo -e "\n" '$@'; print_params $@
	echo -e "\n" '"$*"'; print_params "$*"
        echo -e "\n" '"$@"'; print_params "$@"
}

pass_params "Hey" "I'm mounir from algeria" "i'm a devops engineer"

