#!/bin/bash

# Program to display basic information about a file

PROGRAM="${0##*/}"

if [ -e "$1" ];then
	echo -e "\nFile Info: "
	file "$1"
	echo -e "\nFile Status: "
	stat "$1"
else
	echo "$PROGRAM: $1 not found" >&2
	exit 1
fi
