#!/bin/bash

# display the information of the system depends on user choose menu

PROGNAME="${0##*/}"
TITLE="System information report for $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME by $USER"

usage(){
	echo "$PROGNAME usage is: $PROGNAME [-f filename | -i]"
	return
}
report_uptime(){
	echo "
	<h2>System Uptime</h2>
	<pre>$(uptime)</pre>
	"
	return
}
report_disk_space(){
	echo "
        <h2>Disk Space Utilization/h2>
        <pre>$(df -h)</pre>
        "
        return
}
report_home_space(){
	if (("$(id -u)" == 0));then
        	echo "
			<h2>Home Space Utilization (All Users)/h2>
        		<pre>$(du -sh /home/*)</pre>
       		 "
	else
		echo "
                        <h2>Home Space Utilization ($USER)/h2>
                        <pre>$(du -sh $HOME)</pre>
                 "
	fi
        return
}
write_html_page(){
	echo "
	<html>
		<head>
			<title>$TITLE</title>
		</head>
		<body>
			<h1>$TITLE</h1>
			<p>$TIMESTAMP</p>
			$(report_uptime)
			$(report_disk_space)
			$(report_home_space)
		</body>

	</html>
	"
	return
}

# Process Command Line Options
filename=
interactive=

if [ -n "$1" ];then
	case "$1" in
		-f|--file)	shift
				filename="$1"
				;;
		-i|--interactive)	interactive=1
					;;	
		-h|--help)	usage
				exit
				;;
		*)		usage >&2
				exit 1
				;;
	esac
	shift
fi

if [[ -n "$interactive" ]];then
	while true;do
		read -p "Enter the name of the file " filename
		if [[ -e "$filename" ]];then
			read -p "$filename already exists, override it y/n/q -> "
		       case $REPLY in
		       		y|Y)	break
					;;
				n|N)	continue
					;;
				q|Q)	echo "Program Terminated"
					exit
					;;
				*)    continue
                                        ;;
			esac
		elif [[ -z "$filename" ]];then
			continue
		else
			break
		fi
	done
fi

if [ -n "$filename" ];then
	if touch "$filename" && [ -f "$filename" ];then
		write_html_page > "$filename"
	else
		echo "$PROGNAME can not create file $filename" >&2
		exit 1
	fi
else
	write_html_page
fi





