#!/bin/bash

# demonstrate the different cases of using FOR LOOP

COUNT1=0
COUNT2=0

for i in {1..9};do
	COUNT1=$((COUNT1+i))
done

for ((i=1;i<=9;i=i+1));do
	COUNT2=$((COUNT2+i))
done

echo "COUNT1: $COUNT1"
echo "COUNT2: $COUNT2"


