#!/bin/bash

# display the information of the system depends on user choose menu

PROGNAME="${0##*/}"
TITLE="System information report for $HOSTNAME"
CURRENT_TIME="$(date +"%x %r %Z")"
TIMESTAMP="Generated $CURRENT_TIME by $USER"

usage(){
	echo "$PROGNAME usage is: $PROGNAME [-f filename | -i]"
	return
}
report_uptime(){
	echo "
			<h2>System Uptime</h2>
			<pre>$(uptime)</pre>
	"
	return
}
report_disk_space(){
	local i filesystem size used avail use mounted_on
	echo "<h2>Disk Space Utilization/h2>"
        echo -e "\t\t\t<pre>"
	echo -e "$(df -h)"	
	echo -e "\t\t\t</pre>"
        return
}
report_home_space(){
	local i user_name dir_list i total_files total_dirs total_size
	local format="\t\t\t\t\t%s\t%s\t%s\n"

	if (("$(id -u)" == 0));then
		dir_list="/home/*"
		user_name="All Users"
	else
		dir_list="$HOME"
                user_name="$USER"
	fi

	echo "<h2>Home Space Utilization ($user_name)</h2>"

	for i in $dir_list;do
		total_files="$(find $i -type f | wc -l)"
		total_dirs="$(find $i -type d | wc -l)"
		total_size="$(du -sh $i | cut -f 1)"

		echo -e "\t\t\t\t<h3>$i</h3>"
		echo -e "\t\t\t\t<pre>"
		printf "$format" "Dirs" "Files" "Size"
		printf "$format" "----" "-----" "----"
		printf "$format" "$total_dirs" "$total_files" "$total_size"
		echo -e "\t\t\t\t</pre>"
		echo 
	done
	return
}
write_html_page(){
	echo "
	<html>
		<head>
			<title>$TITLE</title>
		</head>
		<body>
			<h1>$TITLE</h1>
			<p>$TIMESTAMP</p>
			$(report_uptime)
			$(report_disk_space)
			$(report_home_space)
		</body>

	</html>
	"
	return
}

# Process Command Line Options
filename=
interactive=

if [ -n "$1" ];then
	case "$1" in
		-f|--file)	shift
				filename="$1"
				;;
		-i|--interactive)	interactive=1
					;;	
		-h|--help)	usage
				exit
				;;
		*)		usage >&2
				exit 1
				;;
	esac
	shift
fi

if [[ -n "$interactive" ]];then
	while true;do
		read -p "Enter the name of the file " filename
		if [[ -e "$filename" ]];then
			read -p "$filename already exists, override it y/n/q -> "
		       case $REPLY in
		       		y|Y)	break
					;;
				n|N)	continue
					;;
				q|Q)	echo "Program Terminated"
					exit
					;;
				*)    continue
                                        ;;
			esac
		elif [[ -z "$filename" ]];then
			continue
		else
			break
		fi
	done
fi

if [ -n "$filename" ];then
	if touch "$filename" && [ -f "$filename" ];then
		write_html_page > "$filename"
	else
		echo "$PROGNAME can not create file $filename" >&2
		exit 1
	fi
else
	write_html_page
fi





