#!/bin/bash

# arith_loop: script to demonstrate arithmetic operators

a=0
finished=0

printf "a\t\ta^2\t\ta^3\n"

until ((finished));do
	b=$((a**2))
	c=$((a**3))
	printf "%d\t\t%d\t\t%d\n" "$a" "$b" "$c"
	((a<=10?a++:(finished=1)))
done
