#!/bin/bash

# Calculate the loan using bc (Basic Calculator)

PROGNAME="${0##*/}"

usage(){
	cat <<- 4EOF
		Usage: $PROGNAME PRINCIPLE INTEREST MONTHS

		Where:
			PRINCIPLE is the amount of the loan
			INTEREST is the ARP as a number (7% = 0.07)
			MONTHS is the length of the loan's term
	4EOF
}

if (($# != 3));then
	usage
	exit 1
fi

PRINCIPLE=$1
INTEREST=$2
MONTHS=$3

if [[ "$PRINCIPLE" =~ ^[0-9]+\.?[0-9]+?$ && "$INTEREST" =~ ^[0-9]+\.?[0-9]+?$ && "$MONTHS" =~ ^[0-9]+\.?[0-9]+?$ ]];then
	bc <<- EOF4
		scale = 15
		i = $INTEREST / 12
		p = $PRINCIPLE
		n = $MONTHS
		a = p * ((i * ((1+i)^n)) / (((1+i)^n)-1))
		print a, "\n"
	EOF4
else
	echo "PRINCIPLE, INTEREST or MONTHS is not a number"
	exit 1
fi


exit
