#!/bin/bash

# Statistiques of the number of files changed group by hours

PROGNAME="${0##*/}"
error(){
	echo "$1" >&2
	exit 1
}

if [ -z "$1" ];then
        error "usage $PROGNAME DIR_NAME"
fi

if [ ! -d "$1" ];then
	error "The directory $1 doesn't exist"
fi

for i in {1..23};do
	hours[i]=0	
done

for i in $(stat -c %y "$1"/* | cut -c 12-13);do
	j="${i#0}"
	((++hours[j]))
	((++count))
done


# Display Data
echo -e "Hours\t Files\t \t\t Hours\t Files\t"
echo -e "-----\t -----\t \t\t -----\t -----\t"
for i in {1..11};do
	j=$((i+12))
	printf "%d\t %d\t \t\t %d\t %d\n"\
		"$i"\
		"${hours[i]}"\
		"$j"\
		"${hours[j]}"
done

printf "\nThe total number of files is:\t$count"

echo -e "\nProgram ended with success"

exit


