#!/bin/bash
# outputting the entire contents of an array

animals=("lion" "tigger" "rabbit" "camel" "donkey" "monkey" "mule")

echo "Using * without quote"
for i in ${animals[*]};do echo "$i";done
echo -e "-----------------------\n"

echo "Using @ without quote"
for i in ${animals[@]};do echo "$i";done
echo -e "-----------------------\n"

echo "Using * with quote"
for i in "${animals[*]}";do echo "$i";done
echo -e "-----------------------\n"

echo "Using @ with quote"
for i in "${animals[@]}";do echo "$i";done
echo -e "-----------------------\n"

printf "The size of this array is %d\n" "${#animals[@]}"
printf "The size of the Third element is %d\n" "${#animals[2]}"
