#!/bin/bash

# Basic actions with associative array

declare -A colors=([primary]="blue" [secondary]="gray" [success]="green" [alert]="red")

for i in "${colors[@]}";do echo "$i"; done
for i in "${!colors[*]}";do echo "$i"; done
echo -e "---------------------------------\n"

echo -e "Add items"
colors+=([red]="ff0000" [green]="00ff00" [blue]="0000ff")

for i in "${colors[@]}";do echo "$i"; done
for i in "${!colors[*]}";do echo "$i"; done
echo -e "---------------------------------\n"

echo "Delete primary item"
unset "colors[primary]"

for i in "${!colors[@]}";do
	printf "%s ===> %s\n"\
		"$i"\
		"${colors[$i]}"
done

printf "\n"
