#!/bin/bash

# test-integer: evaluate integer version 3

NUMBER=19

if [[ "$NUMBER" =~ ^-?[0-9]+$ ]];then
	if ((NUMBER==0));then
		echo "$NUMBER is equal to ZERO"
	else
		if ((NUMBER<0));then
			echo "$NUMBER is Negative"
		else
			echo "$NUMBER is Positive"
		fi

		if (((NUMBER % 2) != 0));then
			echo "$NUMBER is ODD"
		else
			echo "$NUMBER is EVEN"
		fi
	fi	
else
	echo "$NUMBER is not an Integer" >&2
	exit 1
fi

exit
