#!/bin/bash

# List number of files within a directory group by Owner and GroupOwner


declare -A files file_owner file_group owners groups
Format="%s\t\t %s\t\t %s\n"
PROGNAME="${0##*/}"

if [ ! -d "$1" ];then
	echo "Usage: $PROGNAME Dir_Name" >&2
	exit 1
fi

for i in "$1"/*;do
	owner="$(stat -c %U "$i")"
	group="$(stat -c %G "$i")"
	j="${i##*/}"
	files["$j"]="$j"
	file_owner["$j"]="$owner"
	file_group["$j"]="$group"
	((++owners["$owner"]))
	((++groups["$group"]))
done

echo -e "Total Files in $PROGNAME is ${#files[@]}\n"

# List the collected files
printf "$Format" "Files" "Owner" "Group"
(for i in "${!files[@]}";do
	printf "$Format"\
		"$i"\
		"${file_owner["$i"]}"\
		"${file_group["$i"]}"
done) | sort

# List of Owners
echo -e "\n\nList Of Owners"
for i in "${!owners[@]}";do
	printf "%s : %s files\n" "$i" "${owners["$i"]}"
done

# List of Groups
echo -e "\n\nList Of Groups"
for i in "${!groups[@]}";do
        printf "%s : %s files\n" "$i" "${groups["$i"]}"
done

echo ""


