#!/bin/bash

# Demonstration of Process Substitution

while read attr links owner group size month day time filename;do
	cat <<- 8EOF
		Filename: $filename
		Size: $size
		Owner and Group: $owner $group
		Attributes: $attr
		Links: $links
		Day Month Time: $day $month $day
		--------------------------------
	8EOF
done < <(ls -Althr | tail -n 10)	
