#!/bin/bash

# create temporary files with random names

PROGNAME="${0##*/}"

[ -d $HOME/tmp ] || mkdir $HOME/tmp

name_1="$PROGNAME.$$.$RANDOM"
touch $HOME/tmp/$name_1

name_2=$(mktemp "$HOME/tmp/$PROGNAME.$$.XXXXXX")




