#!/bin/bash

# Asynchronous execution demo (Parent)

echo "Parent: starting ..."
echo "Parent: launching child script"

55-async_child &
pid=$!

echo "Parent: child with pid:$pid launched ..."
echo "Parent: continuing"
sleep 2

echo "Parent: pausing to wait for child to finish ..."
wait "$pid"

echo "Parent: child is finished continuing ..."
echo "Parent: parent is done, exiting"


