#!/bin/bash

# Determine if an integer is within a specified range of values

NUMBER=-45
MIN=15
MAX=26

if [[ "$NUMBER" =~ ^-?[0-9]+$ ]];then
	if [[ "$NUMBER" -ge "$MIN" && "$NUMBER" -le "$MAX" ]];then
		echo "$NUMBER is within $MIN and $MAX"
	else
		echo "$NUMBER is out of range"
	fi
else
	echo "$NUMBER is not an Integer" >&2
	exit 1
fi

exit
