#!/bin/bash

# display basic information

TITLE="Written by $USER in $HOSTNAME"
CURRENT_DATE="$(date +"%x %r %Z")"
TIMESTAMP="Generate in $CURRENT_DATE by $USER"

report_uptime(){
	cat <<- 1EOF
		<h2>System Uptime</h2>
		<pre>$(uptime)</pre>
	1EOF
	return
}

report_disk_space(){
	cat <<- 3EOF
		<h2>Disk Space Utilization</h2>
		<pre>$(df -h)</pre>
	3EOF
	return
}

report_home_space(){
	if [ "$(id -u)" -eq 0 ];then
		cat <<- 6EOF
			<h2>Home Space Utilization</h2>
			<pre>$(du -sh /home/*)</pre>
		6EOF
	else
		cat <<- 6EOF
                        <h2>Home Space Utilization</h2>
                        <pre>$(du -sh $HOME)</pre>
		6EOF
	fi
	return
}

cat <<- 11EOF
	<html>
		<head>
			<title>$TITLE</title>
		</head>
		<body>
			<h1>$TITLE</h1>
			<p>$TIMESTAMP</p>
			<h2>$(report_uptime)</h2>
			<h2>$(report_disk_space)</h2>
			<h2>$(report_home_space)</h2>
		</body>
	<html>
11EOF









