#!/bin/bash

while read rights links owner group size month day time filename;do
	echo "$read $rights $links $owner $group $size $month $day $time $filename"
done < <(find . -maxdepth 1 -type f -iname "*async*" -exec ls -al "{}" ";")
